#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -m 1 &
#nitrogen --restore
#rofi -show drun &
#tint2 &
#numlockx &
#xsetroot -cursor_name left_ptr &
picom &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         4
bspc config window_gap           6

bspc config split_ratio          0.52
#bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color         "#7d7d7d"
bspc config active_border_color         "#4ca4fc"
bspc config focused_border_color        "#8657FF"

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
